/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as DashboardRouteImport } from "./routes/dashboard"
import { Route as BookAMeetingRouteImport } from "./routes/book-a-meeting"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as DashboardIndexRouteImport } from "./routes/dashboard.index"
import { Route as DashboardZonesRouteImport } from "./routes/dashboard.zones"
import { Route as DashboardSettingsRouteImport } from "./routes/dashboard.settings"
import { Route as DashboardPoultryRouteImport } from "./routes/dashboard.poultry"
import { Route as DashboardCropsRouteImport } from "./routes/dashboard.crops"
import { Route as DashboardControlRouteImport } from "./routes/dashboard.control"
import { Route as DashboardAquacultureRouteImport } from "./routes/dashboard.aquaculture"
import { Route as DashboardAnalyticsRouteImport } from "./routes/dashboard.analytics"
import { Route as DashboardAlertsRouteImport } from "./routes/dashboard.alerts"
import { Route as DashboardAdminRouteImport } from "./routes/dashboard.admin"
import { Route as DashboardZonesZoneIdRouteImport } from "./routes/dashboard.zones.$zoneId"

const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any)
const BookAMeetingRoute = BookAMeetingRouteImport.update({
  id: "/book-a-meeting",
  path: "/book-a-meeting",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardZonesRoute = DashboardZonesRouteImport.update({
  id: "/zones",
  path: "/zones",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPoultryRoute = DashboardPoultryRouteImport.update({
  id: "/poultry",
  path: "/poultry",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCropsRoute = DashboardCropsRouteImport.update({
  id: "/crops",
  path: "/crops",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardControlRoute = DashboardControlRouteImport.update({
  id: "/control",
  path: "/control",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAquacultureRoute = DashboardAquacultureRouteImport.update({
  id: "/aquaculture",
  path: "/aquaculture",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: "/analytics",
  path: "/analytics",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAlertsRoute = DashboardAlertsRouteImport.update({
  id: "/alerts",
  path: "/alerts",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardZonesZoneIdRoute = DashboardZonesZoneIdRouteImport.update({
  id: "/$zoneId",
  path: "/$zoneId",
  getParentRoute: () => DashboardZonesRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/book-a-meeting": typeof BookAMeetingRoute
  "/dashboard": typeof DashboardRouteWithChildren
  "/login": typeof LoginRoute
  "/dashboard/admin": typeof DashboardAdminRoute
  "/dashboard/alerts": typeof DashboardAlertsRoute
  "/dashboard/analytics": typeof DashboardAnalyticsRoute
  "/dashboard/aquaculture": typeof DashboardAquacultureRoute
  "/dashboard/control": typeof DashboardControlRoute
  "/dashboard/crops": typeof DashboardCropsRoute
  "/dashboard/poultry": typeof DashboardPoultryRoute
  "/dashboard/settings": typeof DashboardSettingsRoute
  "/dashboard/zones": typeof DashboardZonesRouteWithChildren
  "/dashboard/": typeof DashboardIndexRoute
  "/dashboard/zones/$zoneId": typeof DashboardZonesZoneIdRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/book-a-meeting": typeof BookAMeetingRoute
  "/login": typeof LoginRoute
  "/dashboard/admin": typeof DashboardAdminRoute
  "/dashboard/alerts": typeof DashboardAlertsRoute
  "/dashboard/analytics": typeof DashboardAnalyticsRoute
  "/dashboard/aquaculture": typeof DashboardAquacultureRoute
  "/dashboard/control": typeof DashboardControlRoute
  "/dashboard/crops": typeof DashboardCropsRoute
  "/dashboard/poultry": typeof DashboardPoultryRoute
  "/dashboard/settings": typeof DashboardSettingsRoute
  "/dashboard/zones": typeof DashboardZonesRouteWithChildren
  "/dashboard": typeof DashboardIndexRoute
  "/dashboard/zones/$zoneId": typeof DashboardZonesZoneIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/book-a-meeting": typeof BookAMeetingRoute
  "/dashboard": typeof DashboardRouteWithChildren
  "/login": typeof LoginRoute
  "/dashboard/admin": typeof DashboardAdminRoute
  "/dashboard/alerts": typeof DashboardAlertsRoute
  "/dashboard/analytics": typeof DashboardAnalyticsRoute
  "/dashboard/aquaculture": typeof DashboardAquacultureRoute
  "/dashboard/control": typeof DashboardControlRoute
  "/dashboard/crops": typeof DashboardCropsRoute
  "/dashboard/poultry": typeof DashboardPoultryRoute
  "/dashboard/settings": typeof DashboardSettingsRoute
  "/dashboard/zones": typeof DashboardZonesRouteWithChildren
  "/dashboard/": typeof DashboardIndexRoute
  "/dashboard/zones/$zoneId": typeof DashboardZonesZoneIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/book-a-meeting"
    | "/dashboard"
    | "/login"
    | "/dashboard/admin"
    | "/dashboard/alerts"
    | "/dashboard/analytics"
    | "/dashboard/aquaculture"
    | "/dashboard/control"
    | "/dashboard/crops"
    | "/dashboard/poultry"
    | "/dashboard/settings"
    | "/dashboard/zones"
    | "/dashboard/"
    | "/dashboard/zones/$zoneId"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/book-a-meeting"
    | "/login"
    | "/dashboard/admin"
    | "/dashboard/alerts"
    | "/dashboard/analytics"
    | "/dashboard/aquaculture"
    | "/dashboard/control"
    | "/dashboard/crops"
    | "/dashboard/poultry"
    | "/dashboard/settings"
    | "/dashboard/zones"
    | "/dashboard"
    | "/dashboard/zones/$zoneId"
  id:
    | "__root__"
    | "/"
    | "/book-a-meeting"
    | "/dashboard"
    | "/login"
    | "/dashboard/admin"
    | "/dashboard/alerts"
    | "/dashboard/analytics"
    | "/dashboard/aquaculture"
    | "/dashboard/control"
    | "/dashboard/crops"
    | "/dashboard/poultry"
    | "/dashboard/settings"
    | "/dashboard/zones"
    | "/dashboard/"
    | "/dashboard/zones/$zoneId"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookAMeetingRoute: typeof BookAMeetingRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/dashboard": {
      id: "/dashboard"
      path: "/dashboard"
      fullPath: "/dashboard"
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/book-a-meeting": {
      id: "/book-a-meeting"
      path: "/book-a-meeting"
      fullPath: "/book-a-meeting"
      preLoaderRoute: typeof BookAMeetingRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/dashboard/": {
      id: "/dashboard/"
      path: "/"
      fullPath: "/dashboard/"
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/dashboard/zones": {
      id: "/dashboard/zones"
      path: "/zones"
      fullPath: "/dashboard/zones"
      preLoaderRoute: typeof DashboardZonesRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/dashboard/settings": {
      id: "/dashboard/settings"
      path: "/settings"
      fullPath: "/dashboard/settings"
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/dashboard/poultry": {
      id: "/dashboard/poultry"
      path: "/poultry"
      fullPath: "/dashboard/poultry"
      preLoaderRoute: typeof DashboardPoultryRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/dashboard/crops": {
      id: "/dashboard/crops"
      path: "/crops"
      fullPath: "/dashboard/crops"
      preLoaderRoute: typeof DashboardCropsRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/dashboard/control": {
      id: "/dashboard/control"
      path: "/control"
      fullPath: "/dashboard/control"
      preLoaderRoute: typeof DashboardControlRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/dashboard/aquaculture": {
      id: "/dashboard/aquaculture"
      path: "/aquaculture"
      fullPath: "/dashboard/aquaculture"
      preLoaderRoute: typeof DashboardAquacultureRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/dashboard/analytics": {
      id: "/dashboard/analytics"
      path: "/analytics"
      fullPath: "/dashboard/analytics"
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/dashboard/alerts": {
      id: "/dashboard/alerts"
      path: "/alerts"
      fullPath: "/dashboard/alerts"
      preLoaderRoute: typeof DashboardAlertsRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/dashboard/admin": {
      id: "/dashboard/admin"
      path: "/admin"
      fullPath: "/dashboard/admin"
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/dashboard/zones/$zoneId": {
      id: "/dashboard/zones/$zoneId"
      path: "/$zoneId"
      fullPath: "/dashboard/zones/$zoneId"
      preLoaderRoute: typeof DashboardZonesZoneIdRouteImport
      parentRoute: typeof DashboardZonesRoute
    }
  }
}

interface DashboardZonesRouteChildren {
  DashboardZonesZoneIdRoute: typeof DashboardZonesZoneIdRoute
}

const DashboardZonesRouteChildren: DashboardZonesRouteChildren = {
  DashboardZonesZoneIdRoute: DashboardZonesZoneIdRoute,
}

const DashboardZonesRouteWithChildren = DashboardZonesRoute._addFileChildren(
  DashboardZonesRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardAlertsRoute: typeof DashboardAlertsRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardAquacultureRoute: typeof DashboardAquacultureRoute
  DashboardControlRoute: typeof DashboardControlRoute
  DashboardCropsRoute: typeof DashboardCropsRoute
  DashboardPoultryRoute: typeof DashboardPoultryRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardZonesRoute: typeof DashboardZonesRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardAlertsRoute: DashboardAlertsRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardAquacultureRoute: DashboardAquacultureRoute,
  DashboardControlRoute: DashboardControlRoute,
  DashboardCropsRoute: DashboardCropsRoute,
  DashboardPoultryRoute: DashboardPoultryRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardZonesRoute: DashboardZonesRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookAMeetingRoute: BookAMeetingRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
